#! /bin/sh

ii=0
echo "// this file is autogenerated by makeinit.sh" > cmd/minetest-go/init.go

echo "package main

import (" >> cmd/minetest-go/init.go

while read import; do
	if [ "$import" != "" ] && [ ${import:0:1} != "#"  ]; then	
		echo "	_ \"$import\"" >> cmd/minetest-go/init.go

		go get "$import"
	
		ii=$(echo "$ii + 1" | bc)
	fi
done < load.txt

echo ")
" >> cmd/minetest-go/init.go
