// Code generated by "stringer -type ArgType -linecomment"; DO NOT EDIT.

package help

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArgAny-0]
	_ = x[ArgInt-1]
	_ = x[ArgUInt-2]
	_ = x[ArgBool-3]
	_ = x[ArgPos-4]
	_ = x[ArgString-5]
}

const _ArgType_name = "anyintuintboolposstring"

var _ArgType_index = [...]uint8{0, 3, 6, 10, 14, 17, 23}

func (i ArgType) String() string {
	if i >= ArgType(len(_ArgType_index)-1) {
		return "ArgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArgType_name[_ArgType_index[i]:_ArgType_index[i+1]]
}
