// Code generated by "stringer --type ItemType"; DO NOT EDIT.

package minetest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeNodeItem-0]
	_ = x[TypeSimpleNodeItem-1]
	_ = x[TypeCraftItem-2]
	_ = x[TypeToolItem-3]
}

const _ItemType_name = "TypeNodeItemTypeSimpleNodeItemTypeCraftItemTypeToolItem"

var _ItemType_index = [...]uint8{0, 12, 30, 43, 55}

func (i ItemType) String() string {
	if i >= ItemType(len(_ItemType_index)-1) {
		return "ItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
