// Code generated by "stringer -type=InvLocationType -linecomment"; DO NOT EDIT.

package inventory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvLocationUndefined-0]
	_ = x[InvLocationCurrentPlayer-1]
	_ = x[InvLocationPlayer-2]
	_ = x[InvLocationNodeMeta-3]
	_ = x[InvLocationDetached-4]
}

const _InvLocationType_name = "undefinedcurrent_playerplayernodemetadetached"

var _InvLocationType_index = [...]uint8{0, 9, 23, 29, 37, 45}

func (i InvLocationType) String() string {
	if i >= InvLocationType(len(_InvLocationType_index)-1) {
		return "InvLocationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InvLocationType_name[_InvLocationType_index[i]:_InvLocationType_index[i+1]]
}
